//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flet_Office.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\FletOffice\\\\BeroBreve")]
        public string BeroBreve_Folder {
            get {
                return ((string)(this["BeroBreve_Folder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dokumenter")]
        public string Common_GoDokBib {
            get {
                return ((string)(this["Common_GoDokBib"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\\\\\plaza.local\\\\dfs\\\\EgboligBDK\\\\Egbolig\\\\BDK\\\\Dokumenter i Eg Bolig\\\\Medlem")]
        public string Common_SkabelonSti {
            get {
                return ((string)(this["Common_SkabelonSti"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\MedlemBerobrev nyt_autoprogram.docx")]
        public string BeroBreve_SkabelonNavn {
            get {
                return ((string)(this["BeroBreve_SkabelonNavn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\FletOffice\\\\BeroBreve_old")]
        public string BeroBreve_FolderOld {
            get {
                return ((string)(this["BeroBreve_FolderOld"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\FletOffice\\\\ProgramLog_Bero_")]
        public string BeroBreve_ErrorLog {
            get {
                return ((string)(this["BeroBreve_ErrorLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRO-PLZ-BATCH04")]
        public string Common_MonitorServerNavn {
            get {
                return ((string)(this["Common_MonitorServerNavn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Udskriv BeroBreve")]
        public string BeroBreve_MonitorJobNavn {
            get {
                return ((string)(this["BeroBreve_MonitorJobNavn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gobolig")]
        public string Common_MonitorGruppeNavnGO {
            get {
                return ((string)(this["Common_MonitorGruppeNavnGO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Common_MonitorAlarmVærdiOK {
            get {
                return ((int)(this["Common_MonitorAlarmVærdiOK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Common_MonitorAlarmVærdiFejl {
            get {
                return ((int)(this["Common_MonitorAlarmVærdiFejl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alle breve sendt ok på e-mail i nat")]
        public string Common_MonitorTekstOK {
            get {
                return ((string)(this["Common_MonitorTekstOK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Der er fundet medlemmer uden valid e-mail adresse. Antal ikke sendte breve: ")]
        public string Common_MonitorTekstFejl {
            get {
                return ((string)(this["Common_MonitorTekstFejl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Antal medlemmer, der har fået tilsendt e-mail : ")]
        public string Common_MonitorTekst {
            get {
                return ((string)(this["Common_MonitorTekst"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nogle medlemmer kunne ikke modtage e-mail via batch kørslen  ")]
        public string Common_EmailBodyFejl {
            get {
                return ((string)(this["Common_EmailBodyFejl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Der var ingen medlemmer, der skulle have Bero-breve i dag.")]
        public string BeroBreve_SlutTekstIngen {
            get {
                return ((string)(this["BeroBreve_SlutTekstIngen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nu har vi behandlet medlem nr.: ")]
        public string Common_SlutTekst {
            get {
                return ((string)(this["Common_SlutTekst"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E-mail kunne ikke leveres til medlemsnr. ")]
        public string Common_EmailEjLev {
            get {
                return ((string)(this["Common_EmailEjLev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Officebreve@bdk.dk")]
        public string Common_EmailModtFejl {
            get {
                return ((string)(this["Common_EmailModtFejl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dokument kunne ikke journaliseres for medlemsNr.: ")]
        public string Common_GoboligJourFejl {
            get {
                return ((string)(this["Common_GoboligJourFejl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vi savner din e-mail adresse. ")]
        public string Common_EmailModtIngen1 {
            get {
                return ((string)(this["Common_EmailModtIngen1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("For at forbedre vores service vil vi gerne have lov at sende dig boligtilbud via " +
            "e-mail. Husk derfor at oplyse din e-mail adresse.")]
        public string Common_EmailModtIngen2 {
            get {
                return ((string)(this["Common_EmailModtIngen2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vi har uden held forsøgt at sende dette brev til dig via e-mail adressen: ")]
        public string Common_EmailModtInv {
            get {
                return ((string)(this["Common_EmailModtInv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ingen e-mail adresse angivet for medlemmet")]
        public string Common_EmailIngen {
            get {
                return ((string)(this["Common_EmailIngen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\FletOffice\\\\Opskrivningsbevis")]
        public string Opskrivningsbevis_Folder {
            get {
                return ((string)(this["Opskrivningsbevis_Folder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\BevisSelskab nyt_autoprogram.doc")]
        public string Opskrivningsbevis_SkabelonNavn {
            get {
                return ((string)(this["Opskrivningsbevis_SkabelonNavn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\FletOffice\\\\Opskrivningsbevis_old")]
        public string Opskrivningsbevis_FolderOld {
            get {
                return ((string)(this["Opskrivningsbevis_FolderOld"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\FletOffice\\\\ProgramLog_Opskriv_")]
        public string Opskrivningsbevis_ErrorLog {
            get {
                return ((string)(this["Opskrivningsbevis_ErrorLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Udskriv opskrivningsbeviser")]
        public string Opskrivningsbevis_MonitorJobNavn {
            get {
                return ((string)(this["Opskrivningsbevis_MonitorJobNavn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Admin@bdk.dk")]
        public string Common_EmailAfsFejl {
            get {
                return ((string)(this["Common_EmailAfsFejl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EGinc@bdk.dk")]
        public string Common_EmailEGModtLog {
            get {
                return ((string)(this["Common_EmailEGModtLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BeroBreve fejl!")]
        public string BeroBreve_EmailSubjFejl {
            get {
                return ((string)(this["BeroBreve_EmailSubjFejl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Opskrivningsbevis fejl!")]
        public string Opskrivningsbevis_EmailSubjFejl {
            get {
                return ((string)(this["Opskrivningsbevis_EmailSubjFejl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Der var ingen medlemmer, der skulle have opskrivningsbeviser i dag.")]
        public string Opskrivningsbeviser_SlutTekstIngen {
            get {
                return ((string)(this["Opskrivningsbeviser_SlutTekstIngen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EGbolig")]
        public string Common_MonitorGruppeNavnEG {
            get {
                return ((string)(this["Common_MonitorGruppeNavnEG"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRO-PLZ-SQL02;Initial Catalog=Bolig;Persist Security Info=True;User I" +
            "D=SA-BDK-SPDB;Password=8RUG2plaza")]
        public string Common_ConnectionString_SQL {
            get {
                return ((string)(this["Common_ConnectionString_SQL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRO-PLZ-SQL01;Initial Catalog=PlazaIT;Persist Security Info=True;User" +
            " ID=SA-GOSERVICE;Password=8RUG2plaza")]
        public string Common_ConnectionString_Monitor {
            get {
                return ((string)(this["Common_ConnectionString_Monitor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alle breve leveret OK!")]
        public string Common_EmailSubjOk {
            get {
                return ((string)(this["Common_EmailSubjOk"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alle breve er leveret OK på e-mail.")]
        public string Common_EmailBodyOk {
            get {
                return ((string)(this["Common_EmailBodyOk"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT DISTINCT TOP (100) PERCENT Medlem FROM dbo.MedlemAfSelskabStatusLog AS l WHERE (NyStatus = '1') AND (MedlemSelskab <> 99) AND (CONVERT(date, Createdate) = DATEADD(day, - 1, CONVERT(date, GETDATE()))) AND ((SELECT COUNT(*) AS Antal FROM dbo.MedlemAfSelskabStatusLog AS MedlemAfSelskabStatusLog_1 WHERE (CONVERT(date, Createdate) = DATEADD(day, - 1, CONVERT(date, GETDATE()))) AND (Medlem = l.Medlem) AND (NyStatus = 'l')) = 0) ORDER BY Medlem")]
        public string BeroBreve_Select {
            get {
                return ((string)(this["BeroBreve_Select"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT DISTINCT dbo.MedlemAfSelskab.Medlem, MedlemAfSelskab_1.Sel, MedlemAfSelskab_1.Medlem AS Expr1, MedlemAfSelskab_1.MedlemSelskab, MedlemAfSelskab_1.Status, MedlemAfSelskab_1.DatoOpnot, MedlemAfSelskab_1.DatoBetOpnot, MedlemAfSelskab_1.Lmtype FROM dbo.MedlemAfSelskab RIGHT OUTER JOIN dbo.MedlemAfSelskab AS MedlemAfSelskab_1 ON dbo.MedlemAfSelskab.Medlem = MedlemAfSelskab_1.Medlem 
where datediff(day,MedlemAfSelskab_1.DatoOpnot,getdate()) = 3 and MedlemAfSelskab_1.Status <> 3 and MedlemAfSelskab_1.DatoBetOpnot is not null and datediff(day,MedlemAfSelskab_1.DatoBetOpnot,getdate()) = 3
ORDER BY Medlem, MedlemSelskab, DatoOpnot desc")]
        public string Opskrivningsbevis_Select {
            get {
                return ((string)(this["Opskrivningsbevis_Select"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kism@bdk.dk")]
        public string Common_Email_Testmodt {
            get {
                return ((string)(this["Common_Email_Testmodt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Common_PROD {
            get {
                return ((bool)(this["Common_PROD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Adobe\\Acrobat Reader DC\\Reader\\AcroRd32.exe")]
        public string Common_Adobe_Sti {
            get {
                return ((string)(this["Common_Adobe_Sti"]));
            }
        }
    }
}
